=begin
#Budgea API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for BudgeaClient::OCRApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OCRApi' do
  before do
    # run before each test
    @instance = BudgeaClient::OCRApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OCRApi' do
    it 'should create an instance of OCRApi' do
      expect(@instance).to be_instance_of(BudgeaClient::OCRApi)
    end
  end

  # unit tests for ocr_post
  # Post an image with OCR
  # Post an image and apply OCR on it to obtain found meta-data.&lt;br&gt;&lt;br&gt;
  # @param file File of the document
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id_transaction Transaction used to help OCR to find data
  # @option opts [String] :name Name of the document
  # @return [nil]
  describe 'ocr_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_id_user_ocr_post
  # Post an image with OCR
  # Post an image and apply OCR on it to obtain found meta-data.&lt;br&gt;&lt;br&gt;
  # @param id_user Hint: you can use &#39;me&#39; or &#39;all&#39;
  # @param file File of the document
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id_transaction Transaction used to help OCR to find data
  # @option opts [String] :name Name of the document
  # @return [nil]
  describe 'users_id_user_ocr_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
