# frozen_string_literal: true

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BudgeaClient::HashTable
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'HashTable' do
  before do
    # run before each test
    @instance = BudgeaClient::HashTable.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HashTable' do
    it 'should create an instance of HashTable' do
      expect(@instance).to be_instance_of(BudgeaClient::HashTable)
    end
  end
  describe 'test attribute "wording"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "income"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "display"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "nature"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

