# frozen_string_literal: true

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BudgeaClient::InlineResponse2002
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse2002' do
  before do
    # run before each test
    @instance = BudgeaClient::InlineResponse2002.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse2002' do
    it 'should create an instance of InlineResponse2002' do
      expect(@instance).to be_instance_of(BudgeaClient::InlineResponse2002)
    end
  end
  describe 'test attribute "expires_in"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "auth_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
