# frozen_string_literal: true

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BudgeaClient::InlineResponse20012
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse20012' do
  before do
    # run before each test
    @instance = BudgeaClient::InlineResponse20012.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse20012' do
    it 'should create an instance of InlineResponse20012' do
      expect(@instance).to be_instance_of(BudgeaClient::InlineResponse20012)
    end
  end
  describe 'test attribute "connectors"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

