# frozen_string_literal: true

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BudgeaClient::InlineResponse20028
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse20028' do
  before do
    # run before each test
    @instance = BudgeaClient::InlineResponse20028.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse20028' do
    it 'should create an instance of InlineResponse20028' do
      expect(@instance).to be_instance_of(BudgeaClient::InlineResponse20028)
    end
  end
  describe 'test attribute "transactionsclusters"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

