=begin
#Budgea API Documentation

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BudgeaClient::InlineResponse2009
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse2009' do
  before do
    # run before each test
    @instance = BudgeaClient::InlineResponse2009.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse2009' do
    it 'should create an instance of InlineResponse2009' do
      expect(@instance).to be_instance_of(BudgeaClient::InlineResponse2009)
    end
  end
  describe 'test attribute "connections"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "total"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
